version: '3.8'

services:
  djangoapp:
    restart: always
    build: .
    volumes:
      - static_volume:/app/static:z
      - media_volume:/app/media:z
    networks:
      - nginx_network
      - db_network
    depends_on:
      - db

  nginx:
    restart: always
    image: nginx:stable
    volumes:
      - ./config/nginx:/etc/nginx/conf.d:z
      - static_volume:/app/static:z
      - media_volume:/app/media:z
    depends_on:
      - djangoapp
    networks:
      - nginx_network

  db:
    restart: always
    image: postgres:12
    volumes:
      - db_volume:/var/lib/postgresql/data:z
    networks:
      - db_network

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  db_volume:
  static_volume:
  media_volume:
