# Generated by Django 3.0.8 on 2020-08-01 16:04

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('icon', filebrowser.fields.FileBrowseField(blank=True, help_text='Загружайте изображения в формате 4:3 или 16:9, Размер изображения должен быть более 720 пикселей в высоту', max_length=200, null=True, verbose_name='Иконка категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
